# -*- coding: utf-8 -*-
"""0520_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HHLuq-PIY7Q4VomLkxOVj1-PAFBRo9CK
"""

import io

import pandas as pd
import streamlit as st
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


st.set_page_config(page_title="Fund Comparator", page_icon="📊", layout="wide")

st.markdown(
    """
<style>
    .main { padding-top: 1.5rem; }
    .stDataFrame { border-radius: 8px; }
    thead tr th { background-color: #1a1a1a !important; color: white !important; }
</style>
""",
    unsafe_allow_html=True,
)

st.title("📊 Fund Comparator")
st.caption("Upload Expected Values and Paste Valuation files — compares selected values with a full row audit.")
st.divider()


def normalize_key(value):
    if pd.isna(value):
        return ""
    text = str(value).strip()
    return "" if text.lower() in ("nan", "none") else text


def load_uploaded_file(f, first_col_is_label=False):
    name = f.name.lower()
    if name.endswith(".csv"):
        df = pd.read_csv(f, header=0)
    else:
        df = pd.read_excel(f, sheet_name=0, header=0)

    df.columns = [
        c.strftime("%Y-%m-%d") if hasattr(c, "strftime") else str(c).strip()
        for c in df.columns
    ]

    if first_col_is_label:
        df = df.rename(columns={df.columns[0]: "Label"})

    if "Label" not in df.columns:
        raise ValueError("Could not find a 'Label' column.")

    df["_source_row"] = df.index + 2
    df["_key"] = df["Label"].map(normalize_key)
    df["_occurrence"] = df.groupby("_key", dropna=False).cumcount() + 1
    df["_row_key"] = df["_key"] + " #" + df["_occurrence"].astype(str)
    return df


def valid_keys(df):
    return ~df["_key"].astype(str).str.strip().str.lower().isin(["", "nan", "none"])


def comparable_map(df):
    valid_df = df[valid_keys(df)].copy()
    return valid_df.set_index("_row_key", drop=False).to_dict(orient="index")


def values_match(v1, v2, tolerance):
    if pd.isna(v1) or pd.isna(v2):
        return False

    s1 = str(v1).strip()
    s2 = str(v2).strip()
    if s1.lower() in ("", "nan", "none") or s2.lower() in ("", "nan", "none"):
        return False

    try:
        return abs(float(v1) - float(v2)) <= tolerance
    except (ValueError, TypeError):
        return s1 == s2


def build_excel(df, exp_col, act_col):
    wb = Workbook()
    ws = wb.active
    ws.title = "Comparison"

    green_fill = PatternFill("solid", fgColor="C8E6C9")
    red_fill = PatternFill("solid", fgColor="FFCDD2")
    yellow_fill = PatternFill("solid", fgColor="FFF9C4")
    green_font = Font(bold=True, color="1B5E20")
    red_font = Font(bold=True, color="B71C1C")
    yellow_font = Font(bold=True, color="F57F17")
    hdr_fill = PatternFill("solid", fgColor="212121")
    hdr_font = Font(bold=True, color="FFFFFF")
    thin = Border(
        left=Side(style="thin", color="DDDDDD"),
        right=Side(style="thin", color="DDDDDD"),
        top=Side(style="thin", color="DDDDDD"),
        bottom=Side(style="thin", color="DDDDDD"),
    )

    cols = list(df.columns)
    ws.append(cols)
    for cell in ws[1]:
        cell.fill = hdr_fill
        cell.font = hdr_font
        cell.alignment = Alignment(horizontal="center")
        cell.border = thin

    exp_idx = cols.index(exp_col) if exp_col in cols else -1
    act_idx = cols.index(act_col) if act_col in cols else -1

    for _, row in df.iterrows():
        ws.append([row[c] for c in cols])
        excel_row = ws.max_row
        status = str(row.get("Status", ""))

        if "Match" in status and "Mis" not in status:
            val_fill, val_font = green_fill, green_font
        elif "Mismatch" in status:
            val_fill, val_font = red_fill, red_font
        else:
            val_fill, val_font = yellow_fill, yellow_font

        for col_idx, cell in enumerate(ws[excel_row], start=1):
            cell.border = thin
            cell.alignment = Alignment(horizontal="left")
            if col_idx - 1 in (exp_idx, act_idx):
                cell.fill = val_fill
                cell.font = val_font

    for col_idx, col_cells in enumerate(ws.columns, start=1):
        max_len = max((len(str(c.value or "")) for c in col_cells), default=10)
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 60)

    buf = io.BytesIO()
    wb.save(buf)
    buf.seek(0)
    return buf


st.subheader("Step 1 — Upload your files")
col1, col2 = st.columns(2)

with col1:
    st.markdown("**File 1** — Expected Values")
    file1 = st.file_uploader("Upload File 1", type=["xlsx", "csv"], key="f1", label_visibility="collapsed")

with col2:
    st.markdown("**File 2** — Paste Valuation")
    file2 = st.file_uploader("Upload File 2", type=["xlsx", "csv"], key="f2", label_visibility="collapsed")


df1, df2 = None, None

if file1:
    try:
        df1 = load_uploaded_file(file1)
        with col1:
            st.success(f"✓ {file1.name} — {len(df1):,} rows, {len(df1.columns)} columns")
    except Exception as e:
        with col1:
            st.error(f"Error reading file: {e}")

if file2:
    try:
        df2 = load_uploaded_file(file2, first_col_is_label=True)
        with col2:
            st.success(f"✓ {file2.name} — {len(df2):,} rows, {len(df2.columns)} columns")
    except Exception as e:
        with col2:
            st.error(f"Error reading file: {e}")


if df1 is not None and df2 is not None:
    st.divider()
    st.subheader("Step 2 — Settings")

    audit1_blank = (~valid_keys(df1)).sum()
    audit2_blank = (~valid_keys(df2)).sum()
    audit1_dupes = df1[valid_keys(df1)]["_key"].duplicated(keep=False).sum()
    audit2_dupes = df2[valid_keys(df2)]["_key"].duplicated(keep=False).sum()

    with st.expander("Row audit: why rows may not match", expanded=True):
        a1, a2, a3, a4 = st.columns(4)
        a1.metric("File 1 raw rows", len(df1))
        a2.metric("File 1 blank labels", int(audit1_blank))
        a3.metric("File 2 raw rows", len(df2))
        a4.metric("File 2 blank labels", int(audit2_blank))

        st.caption(
            "Duplicate labels are preserved by adding an occurrence number, for example 'asset value #1' and 'asset value #2'."
        )
        st.write(f"File 1 duplicate-label rows preserved: {int(audit1_dupes):,}")
        st.write(f"File 2 duplicate-label rows preserved: {int(audit2_dupes):,}")

    c1, c2 = st.columns(2)
    with c1:
        shared_value_cols = [c for c in df1.columns if c in df2.columns and c not in ["Label", "_key", "_source_row", "_occurrence", "_row_key"]]
        if not shared_value_cols:
            st.error("No shared comparison columns were found between the two files.")
            st.stop()

        compare_col = st.selectbox(
            "Column to compare",
            shared_value_cols,
            index=shared_value_cols.index("Values") if "Values" in shared_value_cols else 0,
            help="Pick the column you want to compare between the two files. Both files must have this column.",
        )
    with c2:
        tolerance = st.selectbox(
            "Numeric tolerance",
            [0, 0.01, 0.1, 1.0],
            index=1,
            format_func=lambda x: "Exact match only" if x == 0 else f"±{x} (ignore tiny rounding differences)",
        )

    st.divider()
    st.subheader("Step 3 — Run comparison")

    if st.button("▶  Compare files", type="primary", use_container_width=True):
        map1 = comparable_map(df1)
        map2 = comparable_map(df2)

        all_row_keys = list(dict.fromkeys(list(map1.keys()) + list(map2.keys())))

        rows = []
        for row_key in all_row_keys:
            r1 = map1.get(row_key)
            r2 = map2.get(row_key)

            v1 = r1.get(compare_col, "") if r1 else ""
            v2 = r2.get(compare_col, "") if r2 else ""

            if r1 is None:
                status = "missing expected row"
            elif r2 is None:
                status = "missing actual row"
            elif values_match(v1, v2, tolerance):
                status = "match"
            elif str(v1).strip().lower() in ("", "nan", "none") or str(v2).strip().lower() in ("", "nan", "none"):
                status = "missing value"
            else:
                status = "mismatch"

            row = {
                "Status": status,
                "Label": r1.get("_key", "") if r1 else r2.get("_key", ""),
                "Duplicate #": r1.get("_occurrence", "") if r1 else r2.get("_occurrence", ""),
                "File 1 row": r1.get("_source_row", "") if r1 else "",
                "File 2 row": r2.get("_source_row", "") if r2 else "",
                "Value Type": r1.get("Value Type", "") if r1 else (r2.get("Value Type*", "") if r2 else ""),
                "Entity Name": r2.get("Entity Name", "") if r2 else "",
                f"Expected ({compare_col})": v1,
                f"Actual ({compare_col})": v2,
            }
            rows.append(row)

        result_df = pd.DataFrame(rows)
        st.session_state["result_df"] = result_df
        st.session_state["compare_col"] = compare_col


if "result_df" in st.session_state:
    result_df = st.session_state["result_df"]
    compare_col = st.session_state["compare_col"]

    st.divider()
    st.subheader("📋 Results")

    total = len(result_df)
    matched = (result_df["Status"] == "match").sum()
    mismatch = (result_df["Status"] == "mismatch").sum()
    missing = result_df["Status"].isin(["missing value", "missing expected row", "missing actual row"]).sum()

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total comparison rows", total)
    m2.metric("✅ Match", matched)
    m3.metric("🔴 Mismatch", mismatch)
    m4.metric("🟡 Missing", missing)

    st.markdown("---")

    filter_opt = st.radio(
        "Show",
        ["All rows", "Mismatch only", "Match only", "Missing only"],
        horizontal=True,
    )
    filter_map = {
        "All rows": None,
        "Mismatch only": ["mismatch"],
        "Match only": ["match"],
        "Missing only": ["missing value", "missing expected row", "missing actual row"],
    }
    fval = filter_map[filter_opt]
    display_df = result_df if fval is None else result_df[result_df["Status"].isin(fval)]

    exp_col = f"Expected ({compare_col})"
    act_col = f"Actual ({compare_col})"

    def style_table(df):
        styles = pd.DataFrame("", index=df.index, columns=df.columns)
        for i, row in df.iterrows():
            status = row["Status"]
            if status == "match":
                color = "background-color: #c8e6c9; color: #1b5e20"
            elif status == "mismatch":
                color = "background-color: #ffcdd2; color: #b71c1c"
            else:
                color = "background-color: #fff9c4; color: #f57f17"

            for col in [exp_col, act_col]:
                if col in df.columns:
                    styles.at[i, col] = color

        return styles

    display_df = display_df.copy()
    display_df["Status"] = display_df["Status"].map(
        {
            "match": "✅ Match",
            "mismatch": "🔴 Mismatch",
            "missing value": "🟡 Missing value",
            "missing expected row": "🟡 Missing expected row",
            "missing actual row": "🟡 Missing actual row",
        }
    )

    styled = display_df.style.apply(style_table, axis=None)
    st.dataframe(styled, use_container_width=True, height=500)

    st.divider()
    st.subheader("💾 Export results")

    st.download_button(
        label="⬇  Download Excel report (.xlsx)",
        data=build_excel(display_df, exp_col, act_col),
        file_name="fund_comparison_report.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        use_container_width=True,
        type="primary",
    )
    st.caption("🟢 green = values match · 🔴 red = values differ · 🟡 yellow = missing row or value")