# -*- coding: utf-8 -*-
"""0520-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1msulvnI_fb42L5YIojzG_WOPqZB6DN6_
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import io
from openpyxl import Workbook
from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
from openpyxl.utils import get_column_letter

st.set_page_config(page_title="Fund Comparator", page_icon="📊", layout="wide")

st.markdown("""
<style>
    .main { padding-top: 1.5rem; }
    .stDataFrame { border-radius: 8px; }
    thead tr th { background-color: #1a1a1a !important; color: white !important; }
</style>
""", unsafe_allow_html=True)

st.title("📊 Fund Comparator")
st.caption("Upload Expected Values and Paste Valuation files — compares the Values column row by row.")
st.divider()

# ── Step 1: Upload ───────────────────────────────────────────────
st.subheader("Step 1 — Upload your files")
col1, col2 = st.columns(2)

with col1:
    st.markdown("**File 1** — Expected Values")
    file1 = st.file_uploader("Upload File 1", type=["xlsx","csv"], key="f1", label_visibility="collapsed")

with col2:
    st.markdown("**File 2** — Paste Valuation")
    file2 = st.file_uploader("Upload File 2", type=["xlsx","csv"], key="f2", label_visibility="collapsed")


def load_file1(f):
    df = pd.read_excel(f, header=0)
    df.columns = [str(c).strip() if not hasattr(c,'strftime') else c.strftime('%Y-%m-%d') for c in df.columns]
    df['_key'] = df['Label'].astype(str).str.strip()
    return df

def load_file2(f):
    xf = pd.ExcelFile(f)
    sheet = xf.sheet_names[0]
    df = pd.read_excel(f, sheet_name=sheet, header=0)
    df.columns = [str(c).strip() for c in df.columns]
    # First column is the label
    df = df.rename(columns={df.columns[0]: 'Label'})
    df['_key'] = df['Label'].astype(str).str.strip()
    return df


df1, df2 = None, None

if file1:
    try:
        df1 = load_file1(file1)
        with col1:
            st.success(f"✓ {file1.name} — {len(df1):,} rows, {len(df1.columns)} columns")
    except Exception as e:
        with col1:
            st.error(f"Error reading file: {e}")

if file2:
    try:
        df2 = load_file2(file2)
        with col2:
            st.success(f"✓ {file2.name} — {len(df2):,} rows, {len(df2.columns)} columns")
    except Exception as e:
        with col2:
            st.error(f"Error reading file: {e}")


# ── Step 2: Settings ─────────────────────────────────────────────
if df1 is not None and df2 is not None:
    st.divider()
    st.subheader("Step 2 — Settings")
    with st.expander("Debug row counts"):
        st.write("File 1 rows:", len(df1))
        st.write("File 1 unique labels:", df1['_key'].nunique())
        st.write("File 1 blank labels:", df1['_key'].isin(['', 'nan', 'none']).sum())

        st.write("File 2 rows:", len(df2))
        st.write("File 2 unique labels:", df2['_key'].nunique())
        st.write("File 2 blank labels:", df2['_key'].isin(['', 'nan', 'none']).sum())

        dups1 = df1[df1.duplicated('_key', keep=False)].sort_values('_key')
        dups2 = df2[df2.duplicated('_key', keep=False)].sort_values('_key')

        st.write("Duplicate labels in File 1")
        st.dataframe(dups1[['Label', '_key']], use_container_width=True)

        st.write("Duplicate labels in File 2")
        st.dataframe(dups2[['Label', '_key']], use_container_width=True)

    c1, c2 = st.columns(2)
    c1, c2 = st.columns(2)
    with c1:
        # Only show columns that exist in BOTH files
        shared_value_cols = [c for c in df1.columns if c in df2.columns and c not in ['Label','_key']]
        compare_col = st.selectbox(
            "Column to compare",
            shared_value_cols,
            index=shared_value_cols.index('Values') if 'Values' in shared_value_cols else 0,
            help="Pick the column you want to compare between the two files. Both files must have this column."
        )
    with c2:
        tolerance = st.selectbox(
            "Numeric tolerance",
            [0, 0.01, 0.1, 1.0],
            index=1,
            format_func=lambda x: "Exact match only" if x == 0 else f"±{x} (ignore tiny rounding differences)"
        )

    # Extra columns from File 2 to show as context
    f2_context_cols = ['Entity Name', 'Value Type*', 'As Of Date*', 'Methodology*']
    f2_context_cols = [c for c in f2_context_cols if c in df2.columns]

    st.divider()
    st.subheader("Step 3 — Run comparison")

    if st.button("▶  Compare files", type="primary", use_container_width=True):

        map1 = df1.drop_duplicates('_key').set_index('_key').to_dict(orient='index')
        map2 = df2.drop_duplicates('_key').set_index('_key').to_dict(orient='index')

        all_keys = list(dict.fromkeys(
            [k for k in list(map1.keys()) + list(map2.keys())
             if k and k.lower() not in ('nan','none','')]
        ))

        rows = []
        for key in all_keys:
            r1 = map1.get(key)
            r2 = map2.get(key)

            v1 = r1.get(compare_col, '') if r1 else ''
            v2 = r2.get(compare_col, '') if r2 else ''

            # Determine status
            if r1 is None or r2 is None or str(v1).strip() in ('','nan') or str(v2).strip() in ('','nan'):
                status = 'missing'
            else:
                try:
                    status = 'match' if abs(float(v1) - float(v2)) <= tolerance else 'mismatch'
                except (ValueError, TypeError):
                    status = 'match' if str(v1).strip() == str(v2).strip() else 'mismatch'

            row = {
                'Status': status,
                'Label': key,
                'Value Type': r1.get('Value Type','') if r1 else (r2.get('Value Type*','') if r2 else ''),
                'Entity Name': r2.get('Entity Name','') if r2 else '',
                f'Expected ({compare_col})': v1,
                f'Actual ({compare_col})':   v2,
            }
            rows.append(row)

        result_df = pd.DataFrame(rows)
        st.session_state['result_df'] = result_df
        st.session_state['compare_col'] = compare_col


# ── Results ──────────────────────────────────────────────────────
if 'result_df' in st.session_state:
    result_df    = st.session_state['result_df']
    compare_col  = st.session_state['compare_col']

    st.divider()
    st.subheader("📋 Results")

    total    = len(result_df)
    matched  = (result_df['Status'] == 'match').sum()
    mismatch = (result_df['Status'] == 'mismatch').sum()
    missing  = (result_df['Status'] == 'missing').sum()

    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Total rows", total)
    m2.metric("✅ Match", matched)
    m3.metric("🔴 Mismatch", mismatch)
    m4.metric("🟡 No value", missing)

    st.markdown("---")

    filter_opt = st.radio(
        "Show",
        ["All rows", "Mismatch only", "Match only", "No value only"],
        horizontal=True
    )
    filter_map = {
        "All rows": None,
        "Mismatch only": "mismatch",
        "Match only": "match",
        "No value only": "missing"
    }
    fval = filter_map[filter_opt]
    display_df = result_df if fval is None else result_df[result_df['Status'] == fval]

    # Color the value columns based on status
    exp_col = f'Expected ({compare_col})'
    act_col = f'Actual ({compare_col})'

    def style_table(df):
        styles = pd.DataFrame('', index=df.index, columns=df.columns)
        for i, row in df.iterrows():
            status = row['Status']
            if status == 'match':
                color = 'background-color: #c8e6c9; color: #1b5e20'   # green
            elif status == 'mismatch':
                color = 'background-color: #ffcdd2; color: #b71c1c'   # red
            else:
                color = 'background-color: #fff9c4; color: #f57f17'   # yellow

            for col in [exp_col, act_col]:
                if col in df.columns:
                    styles.at[i, col] = color

        return styles

    # Friendly status label
    display_df = display_df.copy()
    display_df['Status'] = display_df['Status'].map({
        'match': '✅ Match',
        'mismatch': '🔴 Mismatch',
        'missing': '🟡 No value'
    })

    styled = display_df.style.apply(style_table, axis=None)
    st.dataframe(styled, use_container_width=True, height=500)

    # ── Export ───────────────────────────────────────────────────
    st.divider()
    st.subheader("💾 Export results")

    def build_excel(df, exp_col, act_col):
        wb = Workbook()
        ws = wb.active
        ws.title = "Comparison"

        green_fill  = PatternFill('solid', fgColor='C8E6C9')
        red_fill    = PatternFill('solid', fgColor='FFCDD2')
        yellow_fill = PatternFill('solid', fgColor='FFF9C4')
        green_font  = Font(bold=True, color='1B5E20')
        red_font    = Font(bold=True, color='B71C1C')
        yellow_font = Font(bold=True, color='F57F17')
        hdr_fill    = PatternFill('solid', fgColor='212121')
        hdr_font    = Font(bold=True, color='FFFFFF')
        thin = Border(
            left=Side(style='thin', color='DDDDDD'), right=Side(style='thin', color='DDDDDD'),
            top=Side(style='thin', color='DDDDDD'), bottom=Side(style='thin', color='DDDDDD')
        )

        cols = list(df.columns)
        ws.append(cols)
        for cell in ws[1]:
            cell.fill = hdr_fill
            cell.font = hdr_font
            cell.alignment = Alignment(horizontal='center')
            cell.border = thin

        exp_idx = cols.index(exp_col) if exp_col in cols else -1
        act_idx = cols.index(act_col) if act_col in cols else -1

        for _, row in df.iterrows():
            ws.append([row[c] for c in cols])
            excel_row = ws.max_row
            status = str(row.get('Status', ''))

            if 'Match' in status and 'Mis' not in status:
                val_fill, val_font = green_fill, green_font
            elif 'Mismatch' in status:
                val_fill, val_font = red_fill, red_font
            else:
                val_fill, val_font = yellow_fill, yellow_font

            for col_idx, cell in enumerate(ws[excel_row], start=1):
                cell.border = thin
                cell.alignment = Alignment(horizontal='left')
                if col_idx - 1 in (exp_idx, act_idx):
                    cell.fill = val_fill
                    cell.font = val_font

        for col_idx, col_cells in enumerate(ws.columns, start=1):
            max_len = max((len(str(c.value or '')) for c in col_cells), default=10)
            ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 60)

        buf = io.BytesIO()
        wb.save(buf)
        buf.seek(0)
        return buf

    st.download_button(
        label="⬇  Download Excel report (.xlsx)",
        data=build_excel(display_df, exp_col, act_col),
        file_name="fund_comparison_report.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        use_container_width=True,
        type="primary"
    )
    st.caption("🟢 green = values match · 🔴 red = values differ · 🟡 yellow = no value found in one or both files")